### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by ontheway1215** [pythonml/house#2]
Traceback (most recent call last):
  File "main.py", line 433, in <module>
    stats()
  File "main.py", line 268, in stats
    avg_build_year = total/count
ZeroDivisionError: division by zero

**Comment by SparkOfLife** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by ontheway1215** [comment]
@SparkOfLife 没有

**Comment by SparkOfLife** [comment]
我已经解决了，原因是没有将抓取的信息存入Mongodb，详情见我修改的[代码](https://github.com/SparkOfLife/house)
